version: '3.8'

services:
  work-os-db:
    image: postgres:15-alpine
    container_name: work-os-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
      POSTGRES_DB: ${DB_NAME:-work_os}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  work-os-web:
    build: .
    container_name: work-os-web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-secret}@work-os-db:5432/${DB_NAME:-work_os}?schema=public
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://34.68.199.234:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-super-secret-key}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    depends_on:
      - work-os-db

volumes:
  pgdata:
